### ISSUE TITLE
Bug: Missing mandatory dependency

### ISSUE THREAD

**Issue by A-K-O-R-A** [jqassistant-tooling/intellij-jqassistant-plugin#69]
![image](https://github.com/user-attachments/assets/32bf8e33-d07c-4aae-8f45-f1eb52da6dda)

**Comment by HolonProduction** [comment]
This is a bug with the plugin verifier, see [this forum post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/21479962703890-JSON-plugin-dependency-cannot-be-resolved).
